version: '3.8'
services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
          - '3000:3000'
        volumes:
            - ./grafana_data:/var/lib/grafana
            - ./grafana_config:/etc/grafana
            - ./csv:/csv
        environment:
            GF_INSTALL_PLUGINS: marcusolsson-csv-datasource
